# LOCAL/GIT CONFIG
# git_url: <GIT_URL>
# git_branch: master
# git_commit_id: 
local_path: ./sample

# PIPELINE CONFIG
seed: 123
repeat: 3

generate_random_number_class: py/GetRandomV0/2/4G
make_dummy_list_class: py/MakeDummyList/2/4G
join_list_to_str_class: py/JoinToStr/2/4G