# LOCAL/GIT CONFIG
# git_url: <GIT_URL>
# git_branch: master
# git_commit_id: 
local_path: ./sample

seed: 123
repeat: 3

gen_random_number_class: R/GetRandomV0
make_dummy_list_class: R/MakeDummyList
join_list_to_str_class: R/JoinToStr